// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: echo.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcJsonTranscondingPerfTest {
  public static partial class EchoService
  {
    static readonly string __ServiceName = "echo.EchoService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest> __Marshaller_echo_SmallPayloadRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse> __Marshaller_echo_SmallPayloadResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest> __Marshaller_echo_MassivePayloadRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse> __Marshaller_echo_MassivePayloadResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest, global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse> __Method_EchoWithSmallPayloadByGet = new grpc::Method<global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest, global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EchoWithSmallPayloadByGet",
        __Marshaller_echo_SmallPayloadRequest,
        __Marshaller_echo_SmallPayloadResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest, global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse> __Method_EchoWithSmallPayloadByPost = new grpc::Method<global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest, global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EchoWithSmallPayloadByPost",
        __Marshaller_echo_SmallPayloadRequest,
        __Marshaller_echo_SmallPayloadResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest, global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse> __Method_EchoWithMassivePayloadByPost = new grpc::Method<global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest, global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EchoWithMassivePayloadByPost",
        __Marshaller_echo_MassivePayloadRequest,
        __Marshaller_echo_MassivePayloadResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcJsonTranscondingPerfTest.EchoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for EchoService</summary>
    public partial class EchoServiceClient : grpc::ClientBase<EchoServiceClient>
    {
      /// <summary>Creates a new client for EchoService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EchoServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EchoService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EchoServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EchoServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EchoServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse EchoWithSmallPayloadByGet(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoWithSmallPayloadByGet(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse EchoWithSmallPayloadByGet(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EchoWithSmallPayloadByGet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse> EchoWithSmallPayloadByGetAsync(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoWithSmallPayloadByGetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse> EchoWithSmallPayloadByGetAsync(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EchoWithSmallPayloadByGet, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse EchoWithSmallPayloadByPost(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoWithSmallPayloadByPost(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse EchoWithSmallPayloadByPost(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EchoWithSmallPayloadByPost, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse> EchoWithSmallPayloadByPostAsync(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoWithSmallPayloadByPostAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcJsonTranscondingPerfTest.SmallPayloadResponse> EchoWithSmallPayloadByPostAsync(global::GrpcJsonTranscondingPerfTest.SmallPayloadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EchoWithSmallPayloadByPost, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse EchoWithMassivePayloadByPost(global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoWithMassivePayloadByPost(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse EchoWithMassivePayloadByPost(global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EchoWithMassivePayloadByPost, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse> EchoWithMassivePayloadByPostAsync(global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EchoWithMassivePayloadByPostAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcJsonTranscondingPerfTest.MassivePayloadResponse> EchoWithMassivePayloadByPostAsync(global::GrpcJsonTranscondingPerfTest.MassivePayloadRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EchoWithMassivePayloadByPost, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override EchoServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EchoServiceClient(configuration);
      }
    }

  }
}
#endregion
